import type { Metadata } from "next";
import "../globals.css";
import { Inter } from "next/font/google";
const inter = Inter({ subsets: ['latin'] });

import { config } from '@fortawesome/fontawesome-svg-core'
import '@fortawesome/fontawesome-svg-core/styles.css'
import HeroFooter from "@/components/hero/footer/footer";
config.autoAddCss = false

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} antialiased`}
      >
        {children}
        <HeroFooter/>
      </body>
    </html>
  );
}
